### PR TITLE
Now builds with ghc 7.10 and 8.0

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by HuwCampbell** [comment]
I'm still getting errors with this on 8 still, will have a better look and get back to you.

**Comment by erikd** [comment]
What errors? You may need to run `./mafia clean` after switching compilers.

**Comment by HuwCampbell** [comment]
Appears that it was just an older version of cabal failing to build one of the transient dependencies. Seems to be working fine now.

**Comment by erikd** [comment]
Ah yes, ghc 8.0 requires cabal >= 1.24.

**Comment by HuwCampbell** [comment]
Thanks, squash and I'll merge.

**Comment by erikd** [comment]
Done!

**Pull request merged**
