### PR TITLE
Adjust bounds

### PR DESCRIPTION
**Pull request by sorki**
Mainly the `text` one in example is causing trouble.

Tested using GHC 9.4.

Also a couple of README, typo fixes.

### CODE REVIEW

**Comment by erikd** [comment]
Looks good. Thanks.

**Comment by tomjaguarpaw** [comment]
Seems like these revisions should be made on Hackage too. Without them it's impossible to depend on grenade from Hackage on modern GHCs. This came up when I was helping someone out on Discourse: https://discourse.haskell.org/t/how-to-create-quickcheck-tests-for-dependently-typed-matrix-addition-without-specifying-each-dimension-statically/9993/3

**Comment by erikd** [comment]
Making this build with `ghc-9.8` and `ghc-9.10` will require code changes and a new upload. I have the ability to merge PRs etc here on Github, but I do not have official upload rights (I however I might be able to do it as a Hackage Trustee).

**Comment by HuwCampbell** [comment]
Yeah as a trustee you definitely could. I can also make the changes to the metadata. The dependencies have shifted a little though, so I'll need to double check them all before hitting go.

**Comment by erikd** [comment]
Supporting `ghc-9.8` and later will need a code update.

**Pull request merged**
