### PR TITLE
bring to lts-5.5

### PR DESCRIPTION
**Pull request by Nolrai**

### CODE REVIEW

**Comment by Nolrai** [comment]
Oh, sorry, I didn't mean to push it to your project! Not entirely sure how
that happened.

**Comment by erikd** [comment]
You submitted a PR, and then pushed more commits to the same branch. All commits to the same branch will considered as part of the same PR.

**Comment by Nolrai** [comment]
Ah. Must have forgotten the pr submitted to you. I later submitted a pr to
my fork with the same branch so sorry about that!

**Comment by erikd** [comment]
Would you like me to cheery pick the just the `stack.yaml` changes?

**Comment by Nolrai** [comment]
That's probably the best idea.

**Comment by erikd** [comment]
Closing in favor of https://github.com/HuwCampbell/grenade/pull/100

**Pull request closed without merging**
